### ISSUE TITLE
阅读界面

### ISSUE THREAD

**Issue by 2363830288** [ytx222/novel-flutter-app#1]
阅读界面完善好了嘛  我想拿走你的阅读界面

**Comment by ytx222** [comment]
emm,没想到这么久了还有人关注
可以直接拿走的,需要注意,翻页方式,仿真的性能较差,覆盖的很好,其他的还没做吧好像,
修改字体大小行距之类的功能是可以用的,其他的有些还没做
躺平中····

**Comment by 2363830288** [comment]
仿真翻页你用的是画布实现的  听说新版flutter  用Fragment Shader 实现仿真性能比较好

**Comment by ytx222** [comment]
可惜我最近懒得维护了,最近工作忙,不过刚好在写flutter,等过一阵忙完了也许可以研究一下,也许继续躺平

**Comment by 2363830288** [comment]
可以加个qq嘛&nbsp; 一起研究 我的qq2363830288

一个人的世界
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ytx222/novel-flutter-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ytx222/novel-flutter-app] 阅读界面 (Issue #1)





 
可惜我最近懒得维护了,最近工作忙,不过刚好在写flutter,等过一阵忙完了也许可以研究一下,也许继续躺平
